version: '3.8'

services:
  mariadb:
    image: mariadb:42
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: ./.env
    volumes:
      - /home/data/mariadb:/var/lib/mysql
    networks:
      - inception
    expose:
      - 3306
    restart: always

  wordpress:
    image: wordpress:42
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: ./.env
    depends_on:
      - mariadb
    volumes:
      - /home/data/wordpress:/var/www/html
    networks:
      - inception
    expose:
      - 9000
    restart: always

  nginx:
    image: nginx:42
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - /home/data/wordpress:/var/www/html
    networks:
      - inception
    restart: always

networks:
  inception:
    driver: bridge
    name: inception